apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storageclass-local-retain.yaml
  - pvc-data.yaml
  - pvc-uploads.yaml
  - deployment.yaml
  - service.yaml
